services:
  db:
    image: postgres:13.4
    hostname: db
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  cloudBeaver:
    image: dbeaver/cloudbeaver:22.3.0
    container_name: cloudbeaver
    hostname: cloudbeaver
    tty: true
    ports:
      - "8978:8978"
    volumes:
      - ./database/cloudbeaver/data:/opt/cloudbeaver/workspace
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: fastapi
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend/app:/app

  frontend:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always 
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    ports:
      - "${NEXT_PORT}:3000"
    volumes:
      - ./frontend/store-nextjs:/app
